use crate::memory_reader::game_data::GameData;
use crate::split_reader::split_reader::Split;

pub trait Splitter: Sized {
    fn should_split(&self) -> impl Fn(&GameData) -> bool;
}

#[rustfmt::skip]
impl Splitter for Split {
    fn should_split(&self) -> impl Fn(&GameData) -> bool {
        match self {
            Split::Manual              => todo!(),
            Split::ChapterA            => todo!(),
            Split::AreaComplete        => todo!(),
            Split::AreaOnEnter         => todo!(),
            Split::AreaOnExit          => todo!(),
            Split::HeartGemAny         => todo!(),
            Split::LevelEnter          => todo!(),
            Split::LevelExit           => todo!(),
            Split::Prologue            => todo!(),
            Split::Chapter1Checkpoint1 => todo!(),
            Split::Chapter1Checkpoint2 => todo!(),
            Split::Chapter1            => todo!(),
            Split::Chapter2Checkpoint1 => todo!(),
            Split::Chapter2Checkpoint2 => todo!(),
            Split::Chapter2            => todo!(),
            Split::Chapter3Checkpoint1 => todo!(),
            Split::Chapter3Checkpoint2 => todo!(),
            Split::Chapter3Checkpoint3 => todo!(),
            Split::Chapter3            => todo!(),
            Split::Chapter4Checkpoint1 => todo!(),
            Split::Chapter4Checkpoint2 => todo!(),
            Split::Chapter4Checkpoint3 => todo!(),
            Split::Chapter4            => todo!(),
            Split::Chapter5Checkpoint1 => todo!(),
            Split::Chapter5Checkpoint2 => todo!(),
            Split::Chapter5Checkpoint3 => todo!(),
            Split::Chapter5Checkpoint4 => todo!(),
            Split::Chapter5            => todo!(),
            Split::Chapter6Checkpoint1 => todo!(),
            Split::Chapter6Checkpoint2 => todo!(),
            Split::Chapter6Checkpoint3 => todo!(),
            Split::Chapter6Checkpoint4 => todo!(),
            Split::Chapter6Checkpoint5 => todo!(),
            Split::Chapter6            => todo!(),
            Split::Chapter7Checkpoint1 => todo!(),
            Split::Chapter7Checkpoint2 => todo!(),
            Split::Chapter7Checkpoint3 => todo!(),
            Split::Chapter7Checkpoint4 => todo!(),
            Split::Chapter7Checkpoint5 => todo!(),
            Split::Chapter7Checkpoint6 => todo!(),
            Split::Chapter7            => todo!(),
            Split::Epilogue            => todo!(),
            Split::Chapter8Checkpoint1 => todo!(),
            Split::Chapter8Checkpoint2 => todo!(),
            Split::Chapter8Checkpoint3 => todo!(),
            Split::Chapter8            => todo!(),
            Split::Chapter9Checkpoint1 => |game_data: &GameData| {game_data.area_id == 10 && game_data.level_name == "a-00"},
            Split::Chapter9Checkpoint2 => |game_data: &GameData| {game_data.area_id == 10 && game_data.level_name == "c-00"},
            Split::Chapter9Checkpoint3 => |game_data: &GameData| {game_data.area_id == 10 && game_data.level_name == "e-00z"},
            Split::Chapter9Checkpoint4 => |game_data: &GameData| {game_data.area_id == 10 && game_data.level_name == "f-door"},
            Split::Chapter9Checkpoint5 => |game_data: &GameData| {game_data.area_id == 10 && game_data.level_name == "h-00b"},
            Split::Chapter9Checkpoint6 => |game_data: &GameData| {game_data.area_id == 10 && game_data.level_name == "i-00"},
            Split::Chapter9Checkpoint7 => |game_data: &GameData| {game_data.area_id == 10 && game_data.level_name == "j-00"},
            Split::Chapter9Checkpoint8 => |game_data: &GameData| {game_data.area_id == 10 && game_data.level_name == "j-16"},
            Split::Chapter9            => |game_data: &GameData| {game_data.area_id == 10 && game_data.chapter_complete},
            Split::Chapter1Cassette    => todo!(),
            Split::Chapter1HeartGem    => todo!(),
            Split::Chapter2Cassette    => todo!(),
            Split::Chapter2HeartGem    => todo!(),
            Split::Chapter3Cassette    => todo!(),
            Split::Chapter3HeartGem    => todo!(),
            Split::Chapter4Cassette    => todo!(),
            Split::Chapter4HeartGem    => todo!(),
            Split::Chapter5Cassette    => todo!(),
            Split::Chapter5HeartGem    => todo!(),
            Split::Chapter6Cassette    => todo!(),
            Split::Chapter6HeartGem    => todo!(),
            Split::Chapter7Cassette    => todo!(),
            Split::Chapter7HeartGem    => todo!(),
            Split::Chapter8Cassette    => todo!(),
            Split::Chapter8HeartGem    => todo!(),
        }
    }
}
